### ISSUE TITLE
Solution seems to be broken

### ISSUE THREAD

**Issue by pbortnick** [learn-co-students/javascript-rock-dodger-bootcamp-prep-000#771]
The solution returns an error: 
` 1) Rock Dodger endGame() removes the "keydown" event listener:
     Error: spy was never called with [ 'keydown', [Function: moveDodger] ]
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toHaveBeenCalledWith (node_modules/expect/lib/Expectation.js:333:28)
      at Context.it (test/index-test.js:173:19)`

**Comment by pbortnick** [comment]
Change 
 `document.removeEventListener('keydown', moveDodger)`
to: 
  `window.removeEventListener('keydown', moveDodger)`
in endGame()
